### ISSUE TITLE
Unable to install from local checkout

### ISSUE THREAD

**Issue by jaraco** [pypa/pep517#22]
In troubleshooting other issues, I'm trying to install from a local checkout of this project, but using pip 18.1, the project doesn't install:

```
$ pip install ~/p/pypa/pep517
Processing /Users/jaraco/p/pypa/pep517
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-req-build-g1rb926g/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/c6/v7hnmq453xb6p2dbz1gqc6rr0000gn/T/pip-req-build-g1rb926g/
```

The [triple verbose output is here](https://gist.github.com/031b04515b79b15344d84bc33cd06a44).

**Comment by jaraco** [comment]
Is this issue with pip?

**Comment by pfmoore** [comment]
You'll need the unreleased master branch of pip to built this project, as it uses flit (and pip's PEP 517 support, which is needed to install flit-based projects, hasn't been released yet).

**Comment by takluyver** [comment]
I thought I'd already done this, but it might be worth switching this back to a `setup.py` build - it's meant to be a core piece of machinery for calling build backends, so it probably makes sense for it to use the most established build backend for its own packaging, to minimise bootstrapping difficulties.

**Comment by pfmoore** [comment]
@takluyver we talked about it a bit, I believe, but it never went any further than that. While I understand your point, to an extent it's good to have a flit-based project in the various PyPA tools, to make sure we don't make any setuptools-specific assumptions. So I'm ambivalent about making the change, personally.

**Comment by takluyver** [comment]
Fair enough. I guess that it's compatible with pip's vendoring system, or we'd have changed it already. :-)

For future reference, if any other packaging tools want to use pep517 and face bootstrapping issues, I wouldn't fight a switch to `setup.py` packaging.

**Comment by pfmoore** [comment]
Pip vendors by downloading the wheel from PyPI, so we don't really care about building ;-)

Same here - I'm OK with someone submitting a PR to switch (assuming there's a good reason to) but I'm not planning on doing anything about it myself.

**Comment by jaraco** [comment]
I'm actually also sympathetic with supporting flit-based installs. I think it's more than worthwhile but actually essential to demonstrating this ~~cutting-edge~~ bleeding-edge functionality.

> You'll need the unreleased master branch of pip

I don't know why I thought pip 18.1 had pep517 build support. Do you know if there are plans to cut a release? I'm attempting to demonstrate use of these tools in my workflow in order to be able to recommend them to others as emergent best practices, so I'm inclined to rely primarily on released versions of code. Would you recommend as a PyPA maintainer running against pip master?

**Comment by KlausErik** [comment]
What is a "unreleased master branch of pip" ?

**Comment by jaraco** [comment]
> What is a "unreleased master branch of pip" ?

That’s what you get when you `pip install git+https://GitHub.com/pypa/pip`.

**Comment by KlausErik** [comment]
Thx :-) - but how do i this on an offline install?

**Comment by jaraco** [comment]
> how do i [install the latest version of pip as found online] on an offline install?

It's not possible in the general case. You can of course clone pip's Github repository and build an sdist with `pyproject-build -s` (from [build](https://pypi.org/project/build)) and then install that sdist in your offline environment, but it's possible that the unrelease master branch will change between when you built the sdist and when you installed in the offline environment.

**Comment by takluyver** [comment]
Perhaps more importantly, the comment saying "You'll need the unreleased master branch of pip" is over two years old. The changes in pip have been released, so you no longer need the master branch. If `pip --version` shows 19.0 or above, it should be fine.

If you have an older version of pip, you can upgrade it with `python3 -m pip install --upgrade pip`. If you need to install it offline, download the files [from PyPI](https://pypi.org/project/pip/#files), or use a command like `pip download pip` on an online machine.

**Comment by KlausErik** [comment]
Hi
I have pip 21.0 installed - and i wanted to install tensorflow - however i need to install offline as i am installing on an AIX platform not connected to the net. Installing tensorflow gave me an error and i landed in this thread. 
I installed some 12 modules offline. Only issue were if the module were compatible with my python3.7 and other modules installed - i managed to find one version of each module to be installed.
This did not work with tensorflow package - all errors were very identical to the output from jaraco's output.

**Comment by takluyver** [comment]
You probably want to talk to the Tensorflow project about how to install it on AIX.

**Comment by KlausErik** [comment]
Yes - will do - thanks for responding anyways ...

**Comment by jaraco** [comment]
In that case, Klaus, it sounds like although your error message is the same, the cause is likely different.

This issue is about an inability to install the `pep517` project with `pip` 18 or earlier.

Since your issue stems from a particularly complicated use-case (last time I installed tensorflow, it was massive), I'd start with that project - find users within tensorflow who can work together with you on the issue. Either that, or I'd distill the issue to a issues that more directly implicate setuptools or pip or pep517.

Good luck.
